#!/usr/bin/python 
# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
#
#   Answer:
#     4613732

fib = [1, 2]
while fib[-1] < 4000000:
    fib.append(fib[-1] + fib[-2])

print sum(i for i in fib[:-1] if i % 2 == 0)
